name: 'Hello World'
description: 'Greet someone'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - id: run-my-stuff
      run: |
        projectID=MJ-jhipster
        projectVersion=1.0.0
        bearerToken=$(curl -k -X 'POST' https://testing.blackduck.synopsys.com/api/tokens/authenticate -H 'Accept: application/vnd.blackducksoftware.user-4+json' -H "Authorization: token ZWI3ZGZlZmItMTlkMS00ODk0LWI1ZTYtY2EwMWNmZjFiMmNmOjM0YWM0N2NhLWI3ZWEtNGE5My05Yjg5LWZlZDdiYTQ2MTE4Zg==" | cut -d '"' -f 4)
        echo Token is $bearerToken
        reportID=$(curl -k -H "Authorization: bearer $bearerToken" -k -X 'POST' "https://testing.blackduck.synopsys/com/api/projects/$projectID/versions/$projectVeersion/sbom-reports" "Content-Type: application/vnd.blackducksoftware.report-4+json")
        echo Report is $reportID
      shell: bash

