name: 'Black Duck SBOM'
description: 'Generate a Black Duck SBOM report'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-number }}
runs:
  using: "composite"
  steps:
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - id: run-my-stuff
      run: |
        projectName=MJ-jhipster
        projectVersion=1.0.0
        bearerToken=$(curl -k -s -X POST https://testing.blackduck.synopsys.com/api/tokens/authenticate -H 'Accept: application/vnd.blackducksoftware.user-4+json' -H "Authorization: token ZWI3ZGZlZmItMTlkMS00ODk0LWI1ZTYtY2EwMWNmZjFiMmNmOjM0YWM0N2NhLWI3ZWEtNGE5My05Yjg5LWZlZDdiYTQ2MTE4Zg==" | cut -d '"' -f 4)
        echo Token is $bearerToken

        projectID=$(curl -k -s -X GET "https://testing.blackduck.synopsys.com/api/projects?q=name:$projectName" -H "Authorization: bearer $bearerToken" -H "Accept: application/vnd.blackducksoftware.project-detail-6+json")

        reportID=$(curl -k -s -X POST https://testing.blackduck.synopsys.com/api/projects/$projectID/versions/$projectVersion/sbom-reports -H "Authorization: bearer $bearerToken")
        echo Report is $reportID
        echo -H "Content-Type: application/vnd.blackducksoftware.report-4+json")
      shell: bash

